import './globals.css'
import Navigation from "./Navigation";
import { useState } from 'react'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gray-900'>
        <div className="flex flex-col relative min-h-screen">
        <Navigation/>
        {children}
        </div>
      </body>
    </html>
  )
}
